// Code generated by Slice Machine. DO NOT EDIT.

import Banner from './Banner';
import Hero from './Hero';
import HeroSlider from './HeroSlider';
import IconGrid from './IconGrid';
import Image from './Image';
import Legal from './Legal';
import LinkMenu from './LinkMenu';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	Banner,
	Hero,
	HeroSlider,
	IconGrid,
	Image,
	Legal,
	LinkMenu,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	banner: Banner,
	hero: Hero,
	hero_slider: HeroSlider,
	icon_grid: IconGrid,
	image: Image,
	legal: Legal,
	link_menu: LinkMenu,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
