// Code generated by Slice Machine. DO NOT EDIT.

import Banner from './Banner';
import BlockQuote from './BlockQuote';
import BlockText from './BlockText';
import Hero from './Hero';
import HeroSlider from './HeroSlider';
import IconGrid from './IconGrid';
import Image from './Image';
import ImageGrid from './ImageGrid';
import Legal from './Legal';
import LinkMenu from './LinkMenu';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	Banner,
	BlockQuote,
	BlockText,
	Hero,
	HeroSlider,
	IconGrid,
	Image,
	ImageGrid,
	Legal,
	LinkMenu,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	banner: Banner,
	block_quote: BlockQuote,
	text: BlockText,
	hero: Hero,
	hero_slider: HeroSlider,
	icon_grid: IconGrid,
	image: Image,
	image_grid: ImageGrid,
	legal: Legal,
	link_menu: LinkMenu,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
